-- ════════════════════════════════════════════════════════════════════════════
-- StartupWeek OS — 4/4 : référentiel Qualiopi (RNQ, 7 critères / 32 indicateurs)
--
-- Libellés : Référentiel national qualité (décret n° 2019-564 et arrêté du 6 juin
-- 2019 modifié) et guide de lecture (version en vigueur). `expectation` résume le
-- niveau attendu du guide de lecture ; à relire avec l'organisme certificateur.
--
-- Périmètre INTERSTELLABS SASU (StartupWeek : actions de formation, sans
-- certification professionnelle, sans apprentissage ni alternance) :
--   • non applicables : 3, 7, 13, 14, 15, 16, 20, 28, 29 ;
--   • nouvel entrant — mise en œuvre auditée à la surveillance (seules les
--     dispositions sont vérifiées à l'audit initial) : 2, 3, 11, 13, 19, 22, 24, 25, 26, 32.
--
-- Idempotent : relancer la migration met à jour les libellés sans toucher au
-- statut, au responsable ni aux notes saisis par l'équipe.
-- ════════════════════════════════════════════════════════════════════════════

insert into crm.qualiopi_indicators
  (id, code, criterion, title, expectation, evidence_hints, status, newcomer_deferred, auto_source)
values
  -- ─── Critère 1 : information du public ───
  ('ind_01', 1, 1,
   'Le prestataire diffuse une information accessible au public, détaillée et vérifiable sur les prestations proposées : prérequis, objectifs, durée, modalités et délais d''accès, tarifs, contacts, méthodes mobilisées et modalités d''évaluation, accessibilité aux personnes handicapées.',
   'Information complète, à jour et accessible (site, programmes, CGV) sur chaque prestation, y compris délais d''accès et conditions d''accessibilité PSH.',
   array['Pages sessions du site (programme, prérequis, objectifs, durée, tarif)', 'CGV et délais d''accès', 'Mention accessibilité / référent handicap', 'Contacts'],
   'a_faire', false, null),
  ('ind_02', 2, 1,
   'Le prestataire diffuse des indicateurs de résultats adaptés à la nature des prestations mises en œuvre et des publics accueillis.',
   'Indicateurs de résultats publiés et actualisés (satisfaction, taux d''abandon, taux de réussite / d''atteinte des objectifs…). Nouvel entrant : dispositions prévues pour les produire et les publier.',
   array['Taux de satisfaction publié sur le site', 'Nombre de stagiaires / sessions', 'Taux d''atteinte des objectifs', 'Date de mise à jour'],
   'a_faire', true, 'resultats_publies'),
  ('ind_03', 3, 1,
   'Lorsque le prestataire met en œuvre des prestations conduisant à une certification professionnelle, il informe sur les taux d''obtention des certifications préparées, les possibilités de valider un ou des blocs de compétences, ainsi que sur les équivalences, passerelles, suites de parcours et les débouchés.',
   'Non applicable : aucune prestation ne conduit à une certification professionnelle (RNCP / RS).',
   array['Justification de non-applicabilité'],
   'non_applicable', true, null),

  -- ─── Critère 2 : objectifs & conception ───
  ('ind_04', 4, 2,
   'Le prestataire analyse le besoin du bénéficiaire en lien avec l''entreprise et/ou le financeur concerné(s).',
   'Analyse du besoin formalisée et tracée pour chaque bénéficiaire (questionnaire de candidature, entretien), prise en compte dans la prestation.',
   array['Formulaire de candidature (motivation, projet, objectifs)', 'Compte rendu d''entretien', 'Échanges avec le financeur / l''entreprise'],
   'a_faire', false, 'analyse_besoin'),
  ('ind_05', 5, 2,
   'Le prestataire définit les objectifs opérationnels et évaluables de la prestation.',
   'Objectifs opérationnels et évaluables formulés pour chaque prestation (verbes d''action, résultats observables).',
   array['Programmes avec objectifs opérationnels', 'Fiches sessions'],
   'a_faire', false, null),
  ('ind_06', 6, 2,
   'Le prestataire établit les contenus et les modalités de mise en œuvre de la prestation, adaptés aux objectifs définis et aux publics bénéficiaires.',
   'Contenus, séquencement, méthodes et modalités (présentiel / distanciel) cohérents avec les objectifs et adaptés aux publics.',
   array['Programme détaillé J1 → J7', 'Déroulé pédagogique', 'Supports'],
   'a_faire', false, null),
  ('ind_07', 7, 2,
   'Lorsque le prestataire met en œuvre des prestations conduisant à une certification professionnelle, il s''assure de l''adéquation du ou des contenus de la prestation aux exigences de la certification visée.',
   'Non applicable : aucune prestation ne conduit à une certification professionnelle.',
   array['Justification de non-applicabilité'],
   'non_applicable', false, null),
  ('ind_08', 8, 2,
   'Le prestataire détermine les procédures de positionnement et d''évaluation des acquis à l''entrée de la prestation.',
   'Procédure de positionnement / évaluation des acquis à l''entrée, adaptée au public, et vérification des prérequis.',
   array['Questionnaire de positionnement', 'Scores de positionnement', 'Vérification des prérequis'],
   'a_faire', false, 'positionnement'),

  -- ─── Critère 3 : accueil, accompagnement, suivi, évaluation ───
  ('ind_09', 9, 3,
   'Le prestataire informe les publics bénéficiaires sur les conditions de déroulement de la prestation.',
   'Information transmise avant l''entrée : convocation (dates, horaires, lieu, accès), règlement intérieur, contacts, modalités pratiques.',
   array['Convocations envoyées', 'Règlement intérieur', 'Livret d''accueil'],
   'a_faire', false, 'convocations'),
  ('ind_10', 10, 3,
   'Le prestataire met en œuvre et adapte la prestation, l''accompagnement et le suivi aux publics bénéficiaires.',
   'Prestation, accompagnement et suivi adaptés aux publics (mentorat, suivi individuel, adaptations tracées).',
   array['Suivi des projets', 'Comptes rendus de mentorat', 'Adaptations individuelles'],
   'a_faire', false, null),
  ('ind_11', 11, 3,
   'Le prestataire évalue l''atteinte par les publics bénéficiaires des objectifs de la prestation.',
   'Évaluation de l''atteinte des objectifs (pitch final, livrables, grille d''évaluation, auto-évaluation). Nouvel entrant : dispositions prévues.',
   array['Grilles d''évaluation (Demo Day)', 'Évaluations des acquis', 'Certificats de réalisation'],
   'a_faire', true, 'evaluations_acquis'),
  ('ind_12', 12, 3,
   'Le prestataire décrit et met en œuvre les mesures pour favoriser l''engagement des bénéficiaires et prévenir les ruptures de parcours.',
   'Mesures décrites et appliquées pour favoriser l''assiduité et prévenir les abandons (suivi des présences, relances, accompagnement).',
   array['Feuilles d''émargement', 'Relances des absents', 'Suivi de l''assiduité'],
   'a_faire', false, 'emargements'),
  ('ind_13', 13, 3,
   'Pour les formations en alternance, le prestataire, en lien avec l''entreprise, anticipe avec l''apprenant les missions confiées, à court, moyen et long terme, et assure la coordination et la progressivité des apprentissages réalisés en centre de formation et en entreprise.',
   'Non applicable : pas de formation en alternance.',
   array['Justification de non-applicabilité'],
   'non_applicable', true, null),
  ('ind_14', 14, 3,
   'Le prestataire met en œuvre un accompagnement socio-professionnel, éducatif et relatif à l''exercice de la citoyenneté.',
   'Non applicable : indicateur spécifique aux CFA.',
   array['Justification de non-applicabilité'],
   'non_applicable', false, null),
  ('ind_15', 15, 3,
   'Le prestataire informe les apprentis de leurs droits et devoirs en tant qu''apprentis et salariés ainsi que des règles applicables en matière de santé et de sécurité en milieu professionnel.',
   'Non applicable : indicateur spécifique aux CFA.',
   array['Justification de non-applicabilité'],
   'non_applicable', false, null),
  ('ind_16', 16, 3,
   'Lorsque le prestataire met en œuvre des formations conduisant à une certification professionnelle, il s''assure que les conditions de présentation des bénéficiaires à la certification respectent les exigences formelles de l''autorité de certification.',
   'Non applicable : aucune prestation ne conduit à une certification professionnelle.',
   array['Justification de non-applicabilité'],
   'non_applicable', false, null),

  -- ─── Critère 4 : moyens pédagogiques, techniques et d'encadrement ───
  ('ind_17', 17, 4,
   'Le prestataire met à disposition ou s''assure de la mise à disposition des moyens humains et techniques adaptés et d''un environnement approprié (conditions, locaux, équipements, plateaux techniques…).',
   'Locaux / lieux, équipements, outils numériques et moyens humains adaptés à chaque session (y compris accessibilité).',
   array['Descriptif des lieux (villa, salles)', 'Liste du matériel et des outils', 'Planning des intervenants'],
   'a_faire', false, null),
  ('ind_18', 18, 4,
   'Le prestataire mobilise et coordonne les différents intervenants internes et/ou externes (pédagogiques, administratifs, logistiques, commerciaux…).',
   'Rôles et coordination des intervenants définis (organigramme, planning, réunions de coordination).',
   array['Organigramme / rôles', 'Planning des intervenants', 'Comptes rendus de coordination'],
   'a_faire', false, null),
  ('ind_19', 19, 4,
   'Le prestataire met à disposition du bénéficiaire des ressources pédagogiques et permet à celui-ci de se les approprier.',
   'Ressources pédagogiques accessibles aux bénéficiaires et modalités d''appropriation (plateforme, kits, templates). Nouvel entrant : dispositions prévues.',
   array['Bibliothèque de ressources participants', 'Accès plateforme', 'Statistiques de téléchargement'],
   'a_faire', true, 'ressources'),
  ('ind_20', 20, 4,
   'Le prestataire dispose d''un personnel dédié à l''appui à la mobilité nationale et internationale, d''un référent handicap et d''un conseil de perfectionnement.',
   'Non applicable : indicateur spécifique aux CFA.',
   array['Justification de non-applicabilité'],
   'non_applicable', false, null),

  -- ─── Critère 5 : compétences des personnels ───
  ('ind_21', 21, 5,
   'Le prestataire détermine, mobilise et évalue les compétences des différents intervenants internes et/ou externes, adaptées aux prestations.',
   'Compétences requises définies, vérifiées (CV, diplômes, expériences) et évaluées pour chaque intervenant.',
   array['CV des intervenants', 'Grille de sélection', 'Évaluations des intervenants'],
   'a_faire', false, 'intervenants_cv'),
  ('ind_22', 22, 5,
   'Le prestataire entretient et développe les compétences de ses salariés, adaptées aux prestations qu''il délivre.',
   'Développement des compétences des salariés planifié et tracé (formations suivies, plan de développement des compétences). Nouvel entrant : dispositions prévues.',
   array['Plan de développement des compétences', 'Attestations de formation', 'Entretiens professionnels'],
   'a_faire', true, 'intervenants_formation'),

  -- ─── Critère 6 : environnement professionnel ───
  ('ind_23', 23, 6,
   'Le prestataire réalise une veille légale et réglementaire sur le champ de la formation professionnelle et en exploite les enseignements.',
   'Veille légale et réglementaire organisée, diffusée en interne et exploitée (évolutions intégrées aux pratiques).',
   array['Registre de veille légale', 'Sources (Légifrance, Centre Inffo…)', 'Actions issues de la veille'],
   'a_faire', false, 'veille'),
  ('ind_24', 24, 6,
   'Le prestataire réalise une veille sur les évolutions des compétences, des métiers et des emplois dans ses secteurs d''intervention et en exploite les enseignements.',
   'Veille métiers / compétences / emplois réalisée et exploitée pour faire évoluer les prestations. Nouvel entrant : dispositions prévues.',
   array['Registre de veille métiers', 'Évolutions de programme liées à la veille'],
   'a_faire', true, 'veille'),
  ('ind_25', 25, 6,
   'Le prestataire réalise une veille sur les innovations pédagogiques et technologiques permettant une évolution de ses prestations et en exploite les enseignements.',
   'Veille pédagogique et technologique (no-code, IA, outils) réalisée et exploitée. Nouvel entrant : dispositions prévues.',
   array['Registre de veille pédagogique / techno', 'Nouveaux outils intégrés aux sessions'],
   'a_faire', true, 'veille'),
  ('ind_26', 26, 6,
   'Le prestataire mobilise les expertises, outils et réseaux nécessaires pour accueillir, accompagner/former ou orienter les publics en situation de handicap.',
   'Référent handicap identifié, réseau de partenaires mobilisable (AGEFIPH, Ressource Handicap Formation…) et adaptations tracées. Nouvel entrant : dispositions prévues.',
   array['Nomination du référent handicap', 'Annuaire des partenaires handicap', 'Besoins d''aménagement recueillis'],
   'a_faire', true, 'handicap'),
  ('ind_27', 27, 6,
   'Lorsque le prestataire fait appel à la sous-traitance ou au portage salarial, il s''assure du respect de la conformité au présent référentiel.',
   'Sélection, contractualisation et suivi des intervenants sous-traitants (freelances) au regard du référentiel.',
   array['Contrats de sous-traitance', 'Charte qualité intervenants', 'Évaluation des sous-traitants'],
   'a_faire', false, null),
  ('ind_28', 28, 6,
   'Lorsque les prestations dispensées au bénéficiaire comprennent des périodes de formation en situation de travail, le prestataire mobilise son réseau de partenaires socio-économiques pour co-construire l''ingénierie de formation et favoriser l''accueil en entreprise.',
   'Non applicable : pas de période de formation en situation de travail.',
   array['Justification de non-applicabilité'],
   'non_applicable', false, null),
  ('ind_29', 29, 6,
   'Le prestataire développe des actions qui concourent à l''insertion professionnelle ou la poursuite d''étude par la voie de l''apprentissage ou par toute autre voie permettant de développer leurs connaissances et leurs compétences.',
   'Non applicable : indicateur spécifique aux CFA.',
   array['Justification de non-applicabilité'],
   'non_applicable', false, null),

  -- ─── Critère 7 : appréciations & réclamations ───
  ('ind_30', 30, 7,
   'Le prestataire recueille les appréciations des parties prenantes : bénéficiaires, financeurs, équipes pédagogiques et entreprises concernées.',
   'Recueil systématique des appréciations (à chaud, à froid, financeurs, intervenants, entreprises) et analyse des résultats.',
   array['Questionnaires de satisfaction à chaud / à froid', 'Retours financeurs et entreprises', 'Synthèses'],
   'a_faire', false, 'satisfaction'),
  ('ind_31', 31, 7,
   'Le prestataire met en œuvre des modalités de traitement des difficultés rencontrées par les parties prenantes, des réclamations exprimées par ces dernières, des aléas survenus en cours de prestation.',
   'Procédure de traitement des réclamations et aléas, registre à jour, accusés de réception et réponses tracés.',
   array['Procédure réclamations', 'Registre des réclamations (REC-AAAA-NNN)', 'Accusés de réception et réponses'],
   'a_faire', false, 'reclamations'),
  ('ind_32', 32, 7,
   'Le prestataire met en œuvre des mesures d''amélioration à partir de l''analyse des appréciations et des réclamations.',
   'Actions d''amélioration identifiées à partir des appréciations et réclamations, suivies et évaluées. Nouvel entrant : dispositions prévues.',
   array['Plan d''amélioration continue', 'Actions correctives tracées', 'Bilan des actions'],
   'a_faire', true, 'amelioration')
on conflict (code) do update set
  criterion         = excluded.criterion,
  title             = excluded.title,
  expectation       = excluded.expectation,
  evidence_hints    = excluded.evidence_hints,
  newcomer_deferred = excluded.newcomer_deferred,
  auto_source       = excluded.auto_source;
